site_name: flip的小站
site_url: https://flip123123.github.io/flip-/
nav:
  - flip的小站: index.md
  - 校内课程:
    - 大一:
      - 形策一: school/1/xc/xc.md
      - 人工智能基础A: school/1/ai/ai.md
    - 大二:
      - 大物实验: school/2/experiment/ex.md
      - 现代管理基础: school/2/management/manage.md
      - 茶文化及茶健康: school/2/tea/tea.md
      - 概统: school/2/stat/stat.md
  - 校外:
    - markdown: learn/md.md
    - 前端:
      - html语法: 
        - 6.16: learn/HTML/html1.md
        - 6.17: learn/HTML/html2.md
        - 6.18: learn/HTML/html3.md
        - 6.22: learn/HTML/html4.md
        - 6.23: learn/HTML/html5.md
      - css:
        - 6.25: learn/css/css1.md
        - 6.26: learn/css/css2.md
        - 6.27: learn/css/css3.md
        - 7.1: learn/css/css4.md
        - 7.3: learn/css/css5.md
        - 7.4: learn/css/css6.md
      - 开发者模式: learn/开发者/开发者模式.md
    - makefile: learn/makefile.md
    - 机械: 
      - solidworks: 
        - 开始: learn/sw/sw.md
        - 草图: learn/sw/草图.md
        - 特征: learn/sw/特征.md
        - 装配: learn/sw/装配体.md
        - 抽屉: learn/sw/抽屉.md
        - 工程图: learn/sw/工程图.md
        - 练习: learn/sw/练习.md
        - 风扇摇头底座: learn/sw/风扇摇头底座设计.md
        - 海豚机械臂: learn/sw/机械臂.md
    - CS: 
      - MIT-Missing-Semester:
        - 课程概览与shell: learn/cs//MIT/1.md
        - shell工具与脚本: learn/cs/MIT/2.md
        - to be continued: learn/cs/MIT/3.md
      - Ng-Machine learning : learn/cs/Ng/1.md
      - wnc的任务: 
        - ssh连接: learn/cs/wnc/ssh.md
        - git&github: learn/cs/wnc/git&github.md
  - 好用: good.md
  - 杂项: 
    - 杂项/搭建.md
    - 杂项/抢票.md
  - 一些talks:
    - 乱七八糟: words/word1.md
    - 工高被刷: words/word2.md
    - 和gsy老师: words/word3.md
    - 社团中心: words/word4.md
    - 是非正缘: words/word5.md
    - 学长组: words/word6.md
theme: 
    name: material
    icon:
      logo: material/feather
    features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.indexes
    - navigation.top
    - navigation.footer
    - search.suggest
    - search.highlight
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.action.view
    - content.footnote.tooltips
    - content.tabs.link
    - header.autohide
    palette:
      scheme: slate
      primary: purple
repo_url: https://github.com/flip123123/flip-
repo_name: flip123123/flip-
markdown_extensions:
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.arithmatex
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - def_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.arithmatex:
      generic: true
extra_javascript:
  - js/extra.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js
extra_css:
  - https://cdn.bootcdn.net/ajax/libs/lxgw-wenkai-screen-webfont/1.7.0/style.min.css
  - extra.css
plugins:
  - statistics

