site_name: flip的小站

nav:
  - 主页: index.md
  - 好用的网址: site.md
  - 学习:
    - 形策一: xc.md
    - 人工智能基础A: ai/ai.md
    - markdown: md.md
    - html语法: 
      - 6.16: HTML/html1.md
      - 6.17: HTML/html2.md
      - 6.18: HTML/html3.md
      - 6.22: HTML/html4.md
      - 6.23: HTML/html5.md
    - makefile: makefile.md
    - css:
      - 6.25: css/css1.md
      - 6.26: css/css2.md
      - 6.27: css/css3.md
      - 7.1: css/css4.md
      - 7.3: css/css5.md
      - 7.4: css/css6.md
  - 一些talks:
    - 乱七八糟: words/word1.md
    - 工高被刷: words/word2.md
    - 和gsy老师: words/word3.md
    - 社团中心: words/word4.md
    - 是非正缘: words/word5.md
theme: 
    name: material
    features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.indexes
    - navigation.path
    - navigation.top
    - navigation.footer
    - search.suggest
    - search.highlight
    - content.code.copy
    palette:
      scheme: slate
      primary: purple

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - def_list

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - css/custom.css