site_name: flip的小站
site_url: https://flip123123.github.io/flip-/
nav:
  - flip的小站: index.md
  - 校内课程:
    - 形策一: school/xc/xc.md
    - 人工智能基础A: school/ai/ai.md
  - 校外:
    - markdown: learn/md.md
    - html语法: 
      - learn/HTML/6.16.md
      - learn/HTML/6.17.md
      - learn/HTML/6.18.md
      - learn/HTML/6.22.md
      - learn/HTML/6.23.md
    - makefile:
      - learn/makefile.md
    - css:
      - learn/css/6.25.md
      - learn/css/6.26.md
      - learn/css/6.27.md
      - learn/css/7.1.md
      - learn/css/7.3.md
      - learn/css/7.4.md
    - 开发者模式: 
      - learn/开发者/开发者模式.md
    - solidworks: 
      - 开始: learn/sw/开始.md
      - 草图: learn/sw/草图.md
      - 特征: learn/sw/特征.md
      - 装配: learn/sw/装配体.md
  - 好用: site.md
  - 杂项: 搭建.md
  - 一些talks:
    - 乱七八糟: words/word1.md
    - 工高被刷: words/word2.md
    - 和gsy老师: words/word3.md
    - 社团中心: words/word4.md
    - 是非正缘: words/word5.md
theme: 
    name: material
    icon:
      logo: material/feather
    features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.indexes
    - navigation.path
    - navigation.top
    - navigation.footer
    - search.suggest
    - search.highlight
    - content.code.copy
    palette:
      scheme: slate
      primary: purple
repo_url: https://github.com/flip123123/flip-
repo_name: flip123123/flip-
markdown_extensions:
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - def_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra_javascript:
  - js/extra.js
extra_css:
  - extra.css

plugins:
  - statistics
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Slowist-Lee/slowist-notebook