site_name: flip的小站

nav:
  - 主页: index.md
  - 我: about.md
  - 好用的网址: site.md
  - 学习:
    - 形策复习: xc.md
    - 人工智能: ai.md
    - md语法: md.md
    - html语法: 
      - 6.16: html1.md
      - 6.17: html2.md
      - 6.18: html3.md
      - 6.22: html4.md
      - 6.23: html5.md

  - 一些talks:
    - 乱七八糟: word1.md
    - 工高被刷: word2.md
    - 和gsy老师: word3.md
    - 社团中心: word4.md
    - 是非正缘: word5.md
theme: 
    name: material
    features:
      - navigation.instant
      - navigation.tabs
      - navigation.tabs.sticky
      - navigation.sections
    palette:
      scheme: slate
      primary: purple

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js