site_name: flip的小站

nav:
  - 主页: index.md
  - 我: about.md
  - 好用的网址: site.md
  - 学习:
    - 形策复习: xc.md
  - 一些talks:
    - 乱七八糟: word1.md
    - 工高被刷: word2.md
    - 和gsy老师: word3.md
    - 社团中心: word4.md
theme: 
    name: material